# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6f5ef548cd5c2e5f48eb45b94f75f4ea4228850724ffd7f19c3cd3468178975dcbf6ce03c2ee224525a280f5d73603af35f91fc0bcf07da9569a1abee25b08d

test:
  secret_key_base: f5b4eb47816f999ab1f43d98d994d50a17122bf7f694385cbc6d65c679acf558b6361bbbcd4837cd625582c48feb9c873c1870958638c9aad6a329b6c2761a00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
